<?php

namespace App\Filament\Nomad\Resources\Notes\Tables;

use App\Actions\Filament\FullPageViewAction;
use App\Actions\Filament\ModalViewAction;
use App\Filament\Helpers\NoteVisibilityColorCallback;
use App\Models\Note;
use Filament\Actions\BulkActionGroup;
use Filament\Actions\DeleteBulkAction;
use Filament\Actions\EditAction;
use Filament\Actions\ForceDeleteBulkAction;
use Filament\Actions\RestoreBulkAction;
use Filament\Support\Icons\Heroicon;
use Filament\Tables\Columns\IconColumn;
use Filament\Tables\Columns\SpatieTagsColumn;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Filters\TrashedFilter;
use Filament\Tables\Table;

class NotesTable
{
    public static function getViewNoteUrl(Note $note): string
    {
        return route('filament.nomad.resources.notes.show', [
            'record' => $note,
        ]);
    }

    public static function configure(Table $table): Table
    {
        return $table
            ->recordClasses(fn (Note $record): string => match (true) {
                $record->isAdminRestricted() => 'note-row-admin-restricted',
                $record->trashed() => 'note-row-trashed',
                default => 'note-row',
            })
            ->persistSortInSession()
            // ->persistSearchInSession()
            // ->persistColumnSearchesInSession()
            ->searchPlaceholder('Search (Name, Title, Slug)')
            ->columns([
                TextColumn::make('user.name')
                    ->searchable(isIndividual: true, isGlobal: true),
                TextColumn::make('title')
                    ->searchable(isIndividual: true, isGlobal: true),
                TextColumn::make('slug')
                    ->searchable(isIndividual: true, isGlobal: true),
                SpatieTagsColumn::make('tags'),
                TextColumn::make('visibility')
                    ->badge()
                    ->color(NoteVisibilityColorCallback::make())
                    ->searchable()
                    ->sortable(),
                IconColumn::make('Deleted')
                    ->boolean()
                    ->state( fn (Note $record): bool => $record->deleted_at === null)
                    ->sortable(['deleted_at'])
                    ->trueIcon(Heroicon::Check)
                    ->falseIcon(Heroicon::ExclamationCircle)
                    ->trueColor('gray'),
                // TODO: add some statistics about the body here, or some autogenerated badges like #img,#php;...
                /*                TextColumn::make('body')
                    ->searchable(),*/
                TextColumn::make('deleted_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
                TextColumn::make('created_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
                TextColumn::make('updated_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
            ])
            ->filters([
                TrashedFilter::make()
                    ->default(),
            ])
            ->recordActions([
                ModalViewAction::make(),
                FullPageViewAction::make(self::getViewNoteUrl(...)),
                EditAction::make(),
            ])
            ->toolbarActions([
                BulkActionGroup::make([
                    DeleteBulkAction::make()
                        ->after( function (): void {
                            /** @var \Livewire\Component $this */
                            // $this->dispatch('refresh-note-list');
                        }),
                    ForceDeleteBulkAction::make(),
                    RestoreBulkAction::make(),
                ]),
            ]);
    }
}
