<?php

namespace App\Filament\Nomad\Resources\Notes\Tables;

use App\Filament\Helpers\NoteVisibilityColorCallback;
use App\Models\Note;
use Filament\Actions\BulkActionGroup;
use Filament\Actions\DeleteBulkAction;
use Filament\Actions\EditAction;
use Filament\Actions\ForceDeleteBulkAction;
use Filament\Actions\RestoreBulkAction;
use Filament\Actions\ViewAction;
use Filament\Support\Enums\IconSize;
use Filament\Support\Icons\Heroicon;
use Filament\Tables\Columns\IconColumn;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Filters\TrashedFilter;
use Filament\Tables\Table;

class NotesTable
{
    public static function configure(Table $table): Table
    {
        return $table
            ->recordClasses(fn (Note $record) => match ($record->trashed()) {
                true => 'border-l-5 !border-l-danger-300 dark:!border-l-danger-900 bg-red-300/20 dark:bg-red-950/20',
                false => 'border-l-5 border-l-green-300 dark:!border-l-green-900 bg-green-300/20 dark:bg-green-950/20',
            })
            ->persistSortInSession()
            //->persistSearchInSession()
            //->persistColumnSearchesInSession()
            ->searchPlaceholder('Search (Name, Title, Slug)')
            ->columns([
                TextColumn::make('user.name')
                    ->searchable(),
                TextColumn::make('visibility')
                    ->searchable()
                    ->badge()
                    ->sortable()
                    ->color(NoteVisibilityColorCallback::make())
                    ,
                TextColumn::make('title')
                    ->searchable(),
                TextColumn::make('slug')
                    ->searchable(),
                IconColumn::make('Deleted')
                    ->boolean()
                    ->state( fn (Note $record): bool => $record->deleted_at === null)
                    ->sortable(['deleted_at'])
                    ->trueIcon(Heroicon::Check)
                    ->falseIcon(Heroicon::ExclamationCircle)
                    ->trueColor('gray')
                    //->size( fn(Note $record) => $record->trashed() ? IconSize::Large : IconSize::ExtraSmall)

                    ,

                //TODO: add some statistics about the body here, or some autogenerated badges like #img,#php;...
/*                TextColumn::make('body')
                    ->searchable(),*/
                TextColumn::make('deleted_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
                TextColumn::make('created_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
                TextColumn::make('updated_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
            ])
            ->filters([
                TrashedFilter::make()
                    ->default()
                    ,
            ])
            ->recordActions([
                ViewAction::make()
                    ->modalHeading("View Note")
                    ->modalDescription(fn ($record) => "\"{$record->title}\"")
                ,
                EditAction::make(),
            ])
            ->toolbarActions([
                BulkActionGroup::make([
                    DeleteBulkAction::make(),
                    ForceDeleteBulkAction::make(),
                    RestoreBulkAction::make(),
                ]),
            ]);
    }
}
